// <auto-generated />
using System;
using AtividadePraticaTCS.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AtividadePraticaTCS.Migrations
{
    [DbContext(typeof(AtividadePraticaTCSContext))]
    [Migration("20220303140031_Update-CodeStatus")]
    partial class UpdateCodeStatus
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AtividadePraticaTCS.Models.Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<int>("StatusId");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.ToTable("Machine");
                });

            modelBuilder.Entity("AtividadePraticaTCS.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.HasKey("Id");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("AtividadePraticaTCS.Models.StatusEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CodeStatus");

                    b.Property<DateTime>("Date");

                    b.Property<int>("MachineId");

                    b.HasKey("Id");

                    b.ToTable("StatusEvent");
                });

            modelBuilder.Entity("AtividadePraticaTCS.Models.Machine", b =>
                {
                    b.HasOne("AtividadePraticaTCS.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
