// <auto-generated />
using System;
using AtividadePraticaTCS.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AtividadePraticaTCS.Migrations
{
    [DbContext(typeof(AtividadePraticaTCSContext))]
    [Migration("20220225160504_OtherEntities")]
    partial class OtherEntities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AtividadePraticaTCS.Models.Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int?>("StatusEventId");

                    b.Property<int?>("StatusId");

                    b.HasKey("Id");

                    b.HasIndex("StatusEventId");

                    b.HasIndex("StatusId");

                    b.ToTable("Machine");
                });

            modelBuilder.Entity("AtividadePraticaTCS.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Code");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("AtividadePraticaTCS.Models.StatusEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<int>("StatusCode");

                    b.HasKey("Id");

                    b.ToTable("StatusEvent");
                });

            modelBuilder.Entity("AtividadePraticaTCS.Models.Machine", b =>
                {
                    b.HasOne("AtividadePraticaTCS.Models.StatusEvent", "StatusEvent")
                        .WithMany("Machines")
                        .HasForeignKey("StatusEventId");

                    b.HasOne("AtividadePraticaTCS.Models.Status", "Status")
                        .WithMany("Machines")
                        .HasForeignKey("StatusId");
                });
#pragma warning restore 612, 618
        }
    }
}
